#server:
#  port: 8080
#spring:
#  application:
#    name: reggie_take_out
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
##      !!!Timezone
#      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: 123456
#mybatis-plus:
#  configuration:
##    user_name-->userName
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      id-type: ASSIGN_ID
#reggie:
##  path: E:\Java_Code\reggie_take_out\src\main\resources\img
#  path: "src/main/resources/img/"

server:
  port: ${PORT:8080}  # Render 需要动态端口

spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:reggie}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${DATABASE_USER:root}
      password: ${DATABASE_PASSWORD:123456}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: ${IMAGE_PATH:/app/static/img/}  # 适配 Render 服务器